### ISSUE TITLE
Unrecognized java version, even though it's Java 11

### ISSUE THREAD

**Issue by realkarmakun** [Cubxity/UnifiedMetrics#34]
Getting this error while using Paper 1.12.2 and java 11 (ghcr.io/pterodactyl/yolks:java_11)
```
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: dev/cubxity/plugins/metrics/bukkit/bootstrap/UnifiedMetricsBukkitBootstrap has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[server.jar:git-Paper-77cce8236]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[server.jar:git-Paper-77cce8236]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[server.jar:git-Paper-77cce8236]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[server.jar:git-Paper-77cce8236]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[server.jar:git-Paper-77cce8236]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[server.jar:git-Paper-77cce8236]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Cubxity** [comment]
This issue has been fixed in 0.3.1-SNAPSHOT. Please try the latest prerelease.
