### ISSUE TITLE
InfluxDB v1.6 Error occured during writing of data

### ISSUE THREAD

**Issue by Gandalf1783** [Cubxity/UnifiedMetrics#59]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues before opening this bug report.

### Current Behavior

Does not insert data, errors out (see log below).

### Expected Behavior

Should insert data into the database

### Server type

Spigot (includes Spigot-based forks)

### Server Version

1.8.9

### Other Mods / Plugins in your server

N/A

### Error log

14:41:38 INFO]: [UnifiedMetrics] Loading UnifiedMetrics v0.3.6
[14:41:38 INFO]: [UnifiedMetrics] Enabling UnifiedMetrics v0.3.6
[14:41:38 INFO]: [UnifiedMetrics] Initializing driver 'influx'.
[14:41:38 INFO]: [UnifiedMetrics] Driver 'influx' initialized (388 ms).
[--- Server initializes further here ---]
[14:41:40 INFO]: Done (1,686s)! For help, type "help" or "?"
[14:41:41 ERROR]: The error occurred during writing of data
dev.cubxity.plugins.metrics.libs.com.influxdb.exceptions.NotFoundException: null
        at dev.cubxity.plugins.metrics.libs.com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:120) ~[unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at dev.cubxity.plugins.metrics.libs.com.influxdb.internal.AbstractRestClient.toInfluxException(AbstractRestClient.java:98) ~[unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at dev.cubxity.plugins.metrics.libs.com.influxdb.client.internal.AbstractWriteClient.lambda$new$12(AbstractWriteClient.java:180) ~[unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.onNext(FlowableDoFinally.java:84) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:284) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.onNext(FlowableConcatMapMaybe.java:137) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber.drain(FlowableConcatMapSingle.java:279) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber.innerSuccess(FlowableConcatMapSingle.java:179) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber$ConcatMapSingleObserver.onSuccess(FlowableConcatMapSingle.java:317) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableCollectSingle$CollectSubscriber.onComplete(FlowableCollectSingle.java:119) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.onComplete(BasicFuseableConditionalSubscriber.java:119) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.checkTerminated(FlowableGroupBy.java:692) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.drainNormal(FlowableGroupBy.java:626) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.drain(FlowableGroupBy.java:559) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.onComplete(FlowableGroupBy.java:549) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupedUnicast.onComplete(FlowableGroupBy.java:474) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupBySubscriber.onComplete(FlowableGroupBy.java:213) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.processors.UnicastProcessor.checkTerminated(UnicastProcessor.java:430) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.processors.UnicastProcessor.drainRegular(UnicastProcessor.java:314) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.processors.UnicastProcessor.drain(UnicastProcessor.java:397) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.processors.UnicastProcessor.onComplete(UnicastProcessor.java:487) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableWindowBoundarySupplier$WindowBoundaryMainSubscriber.drain(FlowableWindowBoundarySupplier.java:254) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableWindowBoundarySupplier$WindowBoundaryMainSubscriber.innerNext(FlowableWindowBoundarySupplier.java:166) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableWindowBoundarySupplier$WindowBoundaryInnerSubscriber.onNext(FlowableWindowBoundarySupplier.java:316) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:360) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:243) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:282) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:668) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableWindowTimed$WindowExactBoundedSubscriber.drainLoop(FlowableWindowTimed.java:498) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.operators.flowable.FlowableWindowTimed$WindowExactBoundedSubscriber$ConsumerIndexHolder.run(FlowableWindowTimed.java:579) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:479) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) [unifiedmetrics-platform-bukkit-0.3.6.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
[--- Error repeats here over and over ---]

### More information

Is it possible that the organisation has to be set for the plugin but is irrelevant for the v1.6 of influx and that this gets confused?

**Comment by Cubxity** [comment]
Influx 1.6 is not supported, use 1.8 or above.

**Comment by Gandalf1783** [comment]
Oh sorry, I didn't see any version requirements. Could you list them in the Readme directly behind the "Metrics" section?

**Comment by Gandalf1783** [comment]
Aside that addition to readme, this issue would be closed and resolved.
