### ISSUE TITLE
Configuration save error causes a different error to emit

### ISSUE THREAD

**Issue by Chiharu-Hagihara** [Cubxity/UnifiedMetrics#60]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues before opening this bug report.

### Current Behavior

Unified Metrics was not working on 1.19.2 server.

### Expected Behavior

Nothing.

### Server type

Spigot (includes Spigot-based forks)

### Server Version

1.19.2

### Other Mods / Plugins in your server

N/A

### Error log

[13:13:53 ERROR]: Error occurred while enabling UnifiedMetrics v0.3.6 (Is it up to date?)
java.lang.IllegalStateException: The UnifiedMetrics plugin is not loaded.
	at dev.cubxity.plugins.metrics.common.plugin.AbstractUnifiedMetricsPlugin.getApiProvider(AbstractUnifiedMetricsPlugin.kt:44) ~[unifiedmetrics-platform-bukkit-0.3.6.jar:?]
	at dev.cubxity.plugins.metrics.common.plugin.AbstractUnifiedMetricsPlugin.enable(AbstractUnifiedMetricsPlugin.kt:55) ~[unifiedmetrics-platform-bukkit-0.3.6.jar:?]
	at dev.cubxity.plugins.metrics.bukkit.bootstrap.UnifiedMetricsBukkitBootstrap.onEnable(UnifiedMetricsBukkitBootstrap.kt:53) ~[unifiedmetrics-platform-bukkit-0.3.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-166]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-166]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:13:53 INFO]: [UnifiedMetrics] Disabling UnifiedMetrics v0.3.6
[13:13:53 ERROR]: Error occurred while disabling UnifiedMetrics v0.3.6 (Is it up to date?)
java.lang.IllegalStateException: The UnifiedMetrics plugin is not loaded.
	at dev.cubxity.plugins.metrics.common.plugin.AbstractUnifiedMetricsPlugin.getApiProvider(AbstractUnifiedMetricsPlugin.kt:44) ~[unifiedmetrics-platform-bukkit-0.3.6.jar:?]
	at dev.cubxity.plugins.metrics.common.plugin.AbstractUnifiedMetricsPlugin.disable(AbstractUnifiedMetricsPlugin.kt:71) ~[unifiedmetrics-platform-bukkit-0.3.6.jar:?]
	at dev.cubxity.plugins.metrics.bukkit.UnifiedMetricsBukkitPlugin.disable(UnifiedMetricsBukkitPlugin.kt:37) ~[unifiedmetrics-platform-bukkit-0.3.6.jar:?]
	at dev.cubxity.plugins.metrics.bukkit.bootstrap.UnifiedMetricsBukkitBootstrap.onDisable(UnifiedMetricsBukkitBootstrap.kt:57) ~[unifiedmetrics-platform-bukkit-0.3.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-166]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-166]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Cubxity** [comment]
Not reproducible on Paper 1.19.2. What server JAR are you using? Are you modifying your server by any means? Are you sure that you don't have other plugins/mods? What version of UnifiedMetrics are you using?

**Comment by Chiharu-Hagihara** [comment]
I use https://api.papermc.io/v2/projects/paper/versions/1.19.2/builds/172/downloads/paper-1.19.2-172.jar this paper. I have not installed any other plugins or mods. UnifiedMetrics is using 0.3.6-platform-bukkit.

**Comment by Cubxity** [comment]
Are you able to send latest.log from your server?

**Comment by Chiharu-Hagihara** [comment]
[latest.log](https://github.com/Cubxity/UnifiedMetrics/files/9640932/latest.log) Yes, this way.

**Comment by Cubxity** [comment]
Resolved. However, this error is caused by another error that occurred whilst saving your configuration file. Please try the pre-release in a few minutes.

**Comment by Chiharu-Hagihara** [comment]
Thanks.
Is it ver.0.3.7?

**Comment by Cubxity** [comment]
> Thanks.
> Is it ver.0.3.7?

Yes.

**Comment by Chiharu-Hagihara** [comment]
[15:01:20 ERROR]: [UnifiedMetrics] An error occurred whilst saving plugin config file
java.io.FileNotFoundException: plugins/UnifiedMetrics/config.yml (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) ~[?:?]
	at java.io.FileOutputStream.open(FileOutputStream.java:293) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:184) ~[?:?]
	at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at dev.cubxity.plugins.metrics.common.plugin.AbstractUnifiedMetricsPlugin.saveConfig(AbstractUnifiedMetricsPlugin.kt:106) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at dev.cubxity.plugins.metrics.common.plugin.AbstractUnifiedMetricsPlugin.enable(AbstractUnifiedMetricsPlugin.kt:54) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at dev.cubxity.plugins.metrics.bukkit.bootstrap.UnifiedMetricsBukkitBootstrap.onEnable(UnifiedMetricsBukkitBootstrap.kt:53) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-166]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-166]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:01:21 INFO]: [UnifiedMetrics] Initializing driver 'influx'.
[15:01:21 ERROR]: [UnifiedMetrics] An error occurred whilst saving driver config file 
java.io.FileNotFoundException: plugins/UnifiedMetrics/driver/influx.yml (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) ~[?:?]
	at java.io.FileOutputStream.open(FileOutputStream.java:293) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:184) ~[?:?]
	at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at dev.cubxity.plugins.metrics.common.api.MetricsManagerImpl.initializeDriver(MetricsManagerImpl.kt:141) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at dev.cubxity.plugins.metrics.common.api.MetricsManagerImpl.initialize(MetricsManagerImpl.kt:57) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at dev.cubxity.plugins.metrics.common.plugin.AbstractUnifiedMetricsPlugin.enable(AbstractUnifiedMetricsPlugin.kt:65) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at dev.cubxity.plugins.metrics.bukkit.bootstrap.UnifiedMetricsBukkitBootstrap.onEnable(UnifiedMetricsBukkitBootstrap.kt:53) ~[unifiedmetrics-platform-bukkit-0.3.7.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-166]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-166]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-166]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
New error.
I ran chmod 777 on the UnifiedMetrics folder to resolve it.

**Comment by Cubxity** [comment]
This is not an error caused by UnifiedMetrics and is out-of-scope for this issue. Ensure your plugins folder have the correct permissions.

**Comment by Chiharu-Hagihara** [comment]
Apparently it was my mistake regarding that error. My apologies. I just got a new error. How about this one?

[15:09:44 WARN]: java.lang.NullPointerException: subscribeActual failed
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5380)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutMainMaybeObserver.otherComplete(MaybeTimeoutMaybe.java:133)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutOtherMaybeObserver.onSuccess(MaybeTimeoutMaybe.java:158)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimer$TimerDisposable.run(MaybeTimer.java:58)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:09:44 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:09:44 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[15:09:44 WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[15:09:44 WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[15:09:44 WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[15:09:44 WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:184)
[15:09:44 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:129)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[15:09:44 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver.onError(MaybeOnErrorNext.java:91)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeMap$MapMaybeObserver.onError(MaybeMap.java:95)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutFallbackMaybeObserver.onError(MaybeTimeoutMaybe.java:195)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeError.subscribeActual(MaybeError.java:35)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
[15:09:44 WARN]: 	... 11 more
[15:09:44 WARN]: Exception in thread "RxNewThreadScheduler-2" java.lang.NullPointerException: subscribeActual failed
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5380)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutMainMaybeObserver.otherComplete(MaybeTimeoutMaybe.java:133)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutOtherMaybeObserver.onSuccess(MaybeTimeoutMaybe.java:158)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimer$TimerDisposable.run(MaybeTimer.java:58)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:09:44 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:09:44 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[15:09:44 WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[15:09:44 WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[15:09:44 WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[15:09:44 WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:184)
[15:09:44 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:129)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[15:09:44 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver.onError(MaybeOnErrorNext.java:91)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeMap$MapMaybeObserver.onError(MaybeMap.java:95)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutFallbackMaybeObserver.onError(MaybeTimeoutMaybe.java:195)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeError.subscribeActual(MaybeError.java:35)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
[15:09:44 WARN]: 	... 11 more
[15:09:44 WARN]: java.lang.NullPointerException: subscribeActual failed
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5380)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutMainMaybeObserver.otherComplete(MaybeTimeoutMaybe.java:133)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutOtherMaybeObserver.onSuccess(MaybeTimeoutMaybe.java:158)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimer$TimerDisposable.run(MaybeTimer.java:58)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:09:44 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:09:44 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[15:09:44 WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[15:09:44 WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[15:09:44 WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[15:09:44 WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:184)
[15:09:44 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:129)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[15:09:44 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver.onError(MaybeOnErrorNext.java:91)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeMap$MapMaybeObserver.onError(MaybeMap.java:95)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutFallbackMaybeObserver.onError(MaybeTimeoutMaybe.java:195)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeError.subscribeActual(MaybeError.java:35)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
[15:09:44 WARN]: 	... 11 more
[15:09:44 WARN]: Exception in thread "RxNewThreadScheduler-2" java.lang.NullPointerException: subscribeActual failed
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5380)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutMainMaybeObserver.otherComplete(MaybeTimeoutMaybe.java:133)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutOtherMaybeObserver.onSuccess(MaybeTimeoutMaybe.java:158)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimer$TimerDisposable.run(MaybeTimer.java:58)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:09:44 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:09:44 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:09:44 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[15:09:44 WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[15:09:44 WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[15:09:44 WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[15:09:44 WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:184)
[15:09:44 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:129)
[15:09:44 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[15:09:44 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver.onError(MaybeOnErrorNext.java:91)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeMap$MapMaybeObserver.onError(MaybeMap.java:95)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutFallbackMaybeObserver.onError(MaybeTimeoutMaybe.java:195)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.internal.operators.maybe.MaybeError.subscribeActual(MaybeError.java:35)
[15:09:44 WARN]: 	at unifiedmetrics-platform-bukkit-0.3.7.jar//io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
[15:09:44 WARN]: 	... 11 more

**Comment by Cubxity** [comment]
`Caused by: java.lang.IllegalStateException: zip file closed` The plugin is not able to find the class required to initialize InfluxDB driver. This is also out-of-scope. Please use the #help channel on [Discord](https://discord.gg/UUPeTMVjV7).
